### ISSUE TITLE
UI have some bugs

### ISSUE THREAD

**Issue by TheMehranKhan** [arian-esl/elontribute#1]
very interesting website bro, I'm guessing it's still on development, I have some problem with the UI because nothing other than an Elon Musk picture is visible, is it intentional? 😂

so much work has gone to making this es  😂

**Comment by arian-esl** [comment]
Thank you for your feedback bro, I'm guessing you didn't scroll down. And Yes! I'm still working on some responsive issues and design problems :)))

**Comment by TheMehranKhan** [comment]
this is such an informative response wow didn't really expected that bro 😂
